export { default as Login } from './User/Login/Login'
export { default as Profile } from './User/Profile/Profile'
export { default as Home } from './Home/Home'
export { default as PrivacyPolicy } from './Agreements/PrivacyPolicy'
export { default as TermsConditions } from './Agreements/TermsConditions'
export { default as ContactUs } from './Contact/ContactUs'
